language: go

go:
  - "1.x"

before_script:
  - curl -L "https://github.com/coreos/etcd/releases/download/v3.4.9/etcd-v3.4.9-linux-amd64.tar.gz" | tar -xzvf - -C /tmp --strip-components=1
  - /tmp/etcd &

before_install:
  - go get github.com/mitchellh/gox

env:
  - GO_ENV=testing ETCD_HOSTS="http://127.0.0.1:2379"

script:
  - go test ./...
  - gox -os="linux" -arch="amd64 386" -output="dist/sand-$TRAVIS_TAG-{{.OS}}-{{.Arch}}/{{.Dir}}" -ldflags="-X main.Version=$TRAVIS_TAG -X github.com/Scalingo/sand/config.Version=$TRAVIS_TAG" ./cmd/...
  - tar -C dist -czvf "dist/sand-$TRAVIS_TAG-linux-386.tar.gz" "sand-$TRAVIS_TAG-linux-386"
  - tar -C dist -czvf "dist/sand-$TRAVIS_TAG-linux-amd64.tar.gz" "sand-$TRAVIS_TAG-linux-amd64"

deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
    repo: Scalingo/sand
  file_glob: true
  file:
    - "dist/*.tar.gz"
  api_key:
    secure: aVX8lPryFz+gHD4JJOK3dQapqNiTPkd8wbycZgoLVgBHLPUYMq/096yEM45in3Xt7btswQpurWKsg3vE/iMEyUEloHw8FnrRQYE9tAE44i3LBxFNDfp55OAkHXlz4yd7DlABAFzdl4ycLNJLDczkPakal3qA02a5IFN8xoYMVMrQtAASDjAcnL6EVXiQAko+IvyMbHb7MMfoDCpaiPGTiAPzo/YXyqW/Cee7OkuOrnrAFEjkme0g4CkP3JW20qiNMwDoJLmeWidSZwBTpvTdqd+RbYBE9dHhkV3/Y4aGw++gvLuSAfUyjAY32y1rHXHx5WhcEftob+w893/ANEB3OC4NpQt1UM7fniCMzXtgU42HhFH9yTG1uE5SokAZcPzAM1ZNpG7kf0qfTjC+1VQFfqeMUzKb11ykL8jiex3WlXpBNyljnS1wgsCQRYGZZI6PLJuZphopKhQKK4nm9CUxS4hGl4K7LgeUNp6cmvNe21e0gMpZ2GPRtUzTiE8hEgJEP+w4m53FVH5TUdTMUTqWS3S1Uxc378E1PBY+dUhSh+3CVynZVwN5VdQQ8Jm5UOQkVltsodfYSTrhlY62nEf3SjOg29ydp/LJrb53SdC2E2bjQTBWX/YoqZyYi7DOR+Vd+reRwV0NFlLqcpKRgoGJFf8uJTxpQ7Qcx9juE+TeauM=
