version: '2'
services:
  web:
    build: .
    pid: "host"
    network_mode: "host"
    privileged: true
    volumes:
      - ./:/go/src/github.com/Scalingo/sand
      - /var/run/netns:/var/run/netns:shared
      - /var/run/docker/netns:/var/run/docker/netns:shared
    environment:
      GO_ENV: development
      ETCD_URL: "http://192.168.254.2:2379"
      PUBLIC_IP: "192.168.254.2"
    ports:
      - 9999:9999
    command: reflex -r '\.go$$' -s -- sh -c 'go install -race && /go/bin/sand'
  etcd:
    image: quay.io/coreos/etcd:v3.2.11
    command: etcd --name etcd-cluster --listen-peer-urls http://0.0.0.0:2380 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://192.168.254.2:2379
    ports:
      - 2379:2379
